# .github/workflows/deploy.yml
name: Deploy Vite Project to GitHub Pages

# Controls when the action will run.
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions granted to the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# The deployment job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies and build the project
      - name: Install dependencies and Build
        run: |
          npm install
          npm run build

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload the final built artifact (the contents of the dist folder)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This must be the directory created by the build step
          path: './dist' 

  # The job to deploy the artifact to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
